# Version of docker compose
version: "3.9"

services:
  playwright:
    image: playwright
    container_name: playwright
    tty: true
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./test-results:/playwright/test-results
      - ./playwright-report:/playwright/playwright-report
      - ./allure-results:/playwright/allure-results