# Version of docker compose
version: "3.9"

services:
  playwright:
    image: qa
    container_name: playwrightDemo
    tty: true
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
      - ./allure-results:/app/allure-results